### PR TITLE
Change DLC settings from opt-out to opt-in.

### PR DESCRIPTION
**Pull request by Gredelston**
Hi @chinhodado -- I believe my colleagues reached out to you about this change. We're using your calculator to support a Persona-related project we're running right now, and we've found that people find opt-in DLC more intuitive. I've tested the change on my local system.

For some reason it's showing commits d7dc11c, 1f87f62, and 449a9fd as part of this PR, even though they were merged in on 11/27/2018 as a91657b.

### CODE REVIEW

**Comment by chinhodado** [comment]
Can you fix up the pull request so that it only contains the relevant change (the 61acb63 commit)?

**Comment by Gredelston** [comment]
Yes, will do tomorrow.

**Comment by Gredelston** [comment]
@chinhodado The diff now only contains the relevant change. Let me know what you think.

Cheers,
Greg

**Comment by chinhodado** [comment]
Thanks, merged

**Pull request merged**
